---
title: "Group Project R Code "
format: gfm
execute:
  warning: false
  message: false
---

# Chronic Disease EHR Dataset

[Link to Dataset](https://www.kaggle.com/datasets/zara2099/chronic-disease-ehr-dataset?resource=download)


```{r}

library(readr)
library(tidyverse)
library(knitr)

chronic_data <- read_csv("Chronic_Disease_EHR_Dataset.csv") 



```
```{r}
chronic_data %>%
  group_by(Patient_ID) %>%
  summarize(n_obs = n(), .groups = "drop") %>%
  summarize(
    n_clusters = n(),                     # number of unique participants
    avg_obs_per_cluster = mean(n_obs)
  ) %>%
  kable() # outputs into nice table :D
```

There are 1750 participants in this dataset. With 4 observations on average per participant. 


# Movie Dataset

[Link to Dataset](https://www.kaggle.com/datasets/grouplens/movielens-20m-dataset/data?select=rating.csv)


```{r}


genome_scores <- read_csv("Movie Datasets/genome_scores.csv")

genome_tags <- read_csv("Movie Datasets/genome_tags.csv")

link <- read_csv("Movie Datasets/link.csv")

rating <- read_csv("Movie Datasets/rating.csv")


rating %>%
  group_by(userId) %>%
  summarize(n_obs = n(), .groups = "drop") %>%
  summarize(
    n_clusters = n(),                     # number of unique participants
    avg_obs_per_cluster = mean(n_obs)
  ) %>%
  kable()



```


